-
  name: Adding new line in /etc/reslove.conf lineinfile
  hosts: all
  become: yes
  tasks:
    -
      name: Update entry into /etc/resolv.conf
      lineinfile:
       path: /etc/resolv.conf
       line: 'nameserver 41.226.22.50'
