---
- hosts: centosA
  become: yes
  tasks:
  - name: Install httpd package
    yum: name=httpd state=latest
  - name: Copy Index.html file
    copy: src=/data/index.html dest=/var/www/html
    notify:
    - restart apache
  - name: Start and enable httpd service
    service: name=httpd state=restarted enabled=yes
  handlers:
  - name: restart apache
    service: name=httpd state=restart

