---
- name: copy multiples lignes
  hosts: all
  tasks:
          - name: copy test
            copy: 
             content: | 
                     line 1
                     line 2 
             dest: /tmp/multiline1.txt
          - name: copy line 2
            copy:
                    content: >
                     line 1 
                     line 2 
                    dest: /tmp/multiline2.txt        
