- hosts: "all"
  become: true

- name: Copy a test file
  hosts: "all"
  tasks:
  - name: copy a test file
    copy:
      src: /var/lib/awx/projects/_8__first_project/upload/test.sh
      dest: /tmp/
      owner: root
      group: root
      mode: '0644'
