---
- name: install start and enable apache2
  hosts: vps3
  tasks:
    - name: install package
      yum:
       name: apache2
       state: latest
    - name: start and enable service
      service:
       name: apache2
       state: started
       enabled: yes
