---
- name: Install and start services
  hosts: ansible1
  tasks:
          - name: Install packages
            yum:
                    name: 
                       - vsftpd
                       - httpd
                    state: latest
          - name: Start the services
            service: 
              name: "{{item}}"
              state: started
              enabled: yes
            loop:
              - vsftpd
              - httpd
