---
- name: install start and enable apache2
  hosts: kalivm
  become: true  
  tasks:
    - name: install package
      apt:
       name: apache2
       state: latest
    - name: start and enable service
      service:
       name: apache2
       state: started
       enabled: yes
