---
- name: Install and start services
  hosts: ansible1
  vars: 
   services:
           - httpd
           - vsftpd
  tasks:
          - name: Install packages
            yum:
                    name: "{{services}}" 
                    state: latest
          - name: Start the services
            service: 
              name: "{{item}}"
              state: started
              enabled: yes
            loop: "{{services}}"
