---
- name: Transfer and execute a script.
  hosts: vps3
  remote_user: root
  tasks:
     - name: Transfer the script
       synchronize: src=iptables.sh dest=/root/iptables.sh 

     - name: Execute the script
       command: sh /root/iptables.sh
