---
- name: Create a user using variable
  hosts: ansible1
  vars:
          users: lisat
  tasks: 
    - name: create a user {{users}} on host {{ansible_hostname}}
      user: 
        name: "{{users }}"
